/*
* Copyright (c) 2019, Spreadtrum Communications.
*
* The above copyright notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANYÂ 
* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THEÂ 
* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#define IPC_CMD_RESPOND_MASK        0x0FFFFFF00
#define IPC_CMD_UNSOLICITE_MASK     0x0000000FE
#define IPC_CMD_RESPOND_BIT_NUM     8


/* add response ID , not more than 7  */
#define IPC_CMD_RESPOND             0x00000001
#define IPC_CMD_UNSOLICITE          0x00000002
#define IPC_CMD_INIT_UNSOLICITE     0x00000004



/* add request command ID */
#define IPC_CMD_REQUEST_INIT   1 << IPC_CMD_RESPOND_BIT_NUM
#define IPC_CMD_REQUEST_OPEN   2 << IPC_CMD_RESPOND_BIT_NUM      
#define IPC_CMD_REQUEST_CLOSE  3 << IPC_CMD_RESPOND_BIT_NUM  


